### ISSUE TITLE
在Paper 1.13上运行有问题

### ISSUE THREAD

**Issue by hank9999** [julyss2019/JulyGuild#3]
您好，2.0.8在1.13上运行基本正常，但是当公会人数多于21人，成员列表会无法打开
```
[16:01:22 ERROR]: Could not pass event InventoryClickEvent to JulyLibrary v2.0.3
java.lang.IndexOutOfBoundsException: Index: 21, Size: 21
        at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_211]
        at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_211]
        at com.github.julyss2019.mcsp.julyguild.gui.entities.GuildMemberListGUI.createInventory(GuildMemberListGUI.java:131) ~[?:?]
        at com.github.julyss2019.mcsp.julyguild.gui.GUI.open(GUI.java:72) ~[?:?]
        at com.github.julyss2019.mcsp.julyguild.gui.PageableGUI.open(PageableGUI.java:108) ~[?:?]
        at com.github.julyss2019.mcsp.julyguild.gui.entities.GuildMineGUI$3.onClick(GuildMineGUI.java:73) ~[?:?]
        at com.github.julyss2019.mcsp.julylibrary.inventory.InventoryBuilderListener.onInventoryClickEvent(InventoryBuilderListener.java:63) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor664.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-655]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-655]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-655]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-655]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2288) ~[patched_1.13.2.jar:git-Paper-655]
        at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.13.2.jar:git-Paper-655]
        at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.13.2.jar:git-Paper-655]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-655]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_211]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_211]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-655]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-655]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-655]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-655]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-655]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
```
但是2.0.8以上版本在Paper上不保留之前的配置文件运行均会缺少材质
```
[15:17:15] [Server thread/INFO]: [JulyGuild] [WARNING] material 不合法, 路径: 'other_items.glass.icon'.
[15:17:15] [Server thread/INFO]: [JulyGuild] [WARNING] material 不合法, 路径: 'other_items.glass.icon'.
[15:17:15] [Server thread/INFO]: [JulyGuild] [WARNING] material 不合法, 路径: 'other_items.glass.icon'.
[15:17:15] [Server thread/INFO]: [JulyGuild] [WARNING] material 不合法, 路径: 'other_items.glass.icon'.
[15:17:15] [Server thread/INFO]: [JulyGuild] [WARNING] material 不合法, 路径: 'other_items.glass.icon'.
[15:17:21] [Server thread/INFO]: [JulyGuild] [WARNING] material 不合法, 路径: 'items.members.icon'.
[15:17:21] [Server thread/INFO]: [JulyGuild] [WARNING] skull_owner 不合法, 因为 material 不是头颅, 路径: 'items.members.icon'.
```
保留配置文件会直接报错无法加载  
```
[15:14:59] [Server thread/ERROR]: Error occurred while enabling JulyGuild v2.1.1 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.SKULL_ITEM
	at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_241]
	at org.bukkit.Material.valueOf(Material.java:77) ~[patched_1.13.2.jar:git-Paper-655]
	at com.github.julyss2019.mcsp.julyguild.guild.GuildIcon.<init>(GuildIcon.java:23) ~[?:?]
	at com.github.julyss2019.mcsp.julyguild.guild.Guild.loadIcons(Guild.java:158) ~[?:?]
	at com.github.julyss2019.mcsp.julyguild.guild.Guild.load(Guild.java:93) ~[?:?]
	at com.github.julyss2019.mcsp.julyguild.guild.Guild.<init>(Guild.java:59) ~[?:?]
	at com.github.julyss2019.mcsp.julyguild.guild.GuildManager.loadGuild(GuildManager.java:94) ~[?:?]
	at com.github.julyss2019.mcsp.julyguild.guild.GuildManager.loadGuilds(GuildManager.java:125) ~[?:?]
	at com.github.julyss2019.mcsp.julyguild.JulyGuild.onEnable(JulyGuild.java:164) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.13.2.jar:git-Paper-655]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[patched_1.13.2.jar:git-Paper-655]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) ~[patched_1.13.2.jar:git-Paper-655]
	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366) ~[?:?]
	at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114) ~[?:?]
	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-655]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.13.2.jar:git-Paper-655]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734) ~[patched_1.13.2.jar:git-Paper-655]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:696) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.DedicatedServer.handleCommandQueue(DedicatedServer.java:483) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:440) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-655]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
[15:14:59] [Server thread/INFO]: [JulyGuild] Disabling JulyGuild v2.1.1
[15:14:59] [Server thread/INFO]: [JulyGuild] [INFO] 插件被卸载.
```

**Comment by julyss2019** [comment]
问题1已在v2.1.1已修复。
v2.1.1版本相对于低版本有较大的配置改动，删除 config 文件夹重新生成即可。
material 不合法是因为插件默认配置是基于1.12.2的，高版本有改动，/guild helper 可以帮助配置配置文件。
